### ISSUE TITLE
(bug): Normalization does not work

### ISSUE THREAD

**Issue by macrintr** [seung-lab/corgie#1]
@nkemnitz wasn't able to use the json-backend branch (now master) for the last normalization step (corgie log, line 536). Traceback:
```
Write to JSON gs://tmacrina-corgie-test/fafbv15_per_island/affine_blockmatch_combined_v1/complete_mip6/mean_normalized/section_value/chunk_mean, z: range(7062, 7063)
Starting execution of <class 'corgie.cli.compute_stats.ComputeStatsTask'>
Traceback (most recent call last):
  File "/opt/conda/bin/corgie-worker", line 11, in <module>
    load_entry_point('corgie', 'console_scripts', 'corgie-worker')()
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/corgie/corgie/worker.py", line 18, in worker
    executor.execute(lease_seconds=lease_seconds)
  File "/opt/corgie/src/mazepa/mazepa/executor.py", line 16, in execute
    self.queue.poll_tasks(lease_seconds=lease_seconds)
  File "/opt/corgie/src/mazepa/mazepa/queue.py", line 232, in poll_tasks
    self.queue.poll(lease_seconds=lease_seconds)
  File "/opt/conda/lib/python3.7/site-packages/taskqueue/taskqueue.py", line 375, in poll
    task.execute(*execute_args, **execute_kwargs)
  File "/opt/corgie/src/mazepa/mazepa/queue.py", line 43, in execute
    task.execute()
  File "/opt/corgie/corgie/cli/compute_stats.py", line 151, in execute
    channel_end=self.write_channel + 1)
  File "/opt/corgie/corgie/layers/volumetric_layers.py", line 55, in write
    super().write(data_tens=data_tens, bcube=indexed_bcube, mip=mip, **kwargs)
  File "/opt/corgie/corgie/layers/base.py", line 65, in write
    self.write_backend(data_np, **kwargs)
  File "/opt/corgie/corgie/data_backends/json.py", line 60, in write_backend
    self.cf.put_jsons(zip(filepaths, data), cache_control='no-cache')
  File "/opt/conda/lib/python3.7/site-packages/cloudfiles/cloudfiles.py", line 578, in put_jsons
    progress=progress, parallel=parallel
  File "/opt/conda/lib/python3.7/site-packages/cloudfiles/cloudfiles.py", line 85, in inner_decor
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/cloudfiles/cloudfiles.py", line 508, in puts
    green=self.green,
  File "/opt/conda/lib/python3.7/site-packages/cloudfiles/scheduler.py", line 113, in schedule_jobs
    return schedule_threaded_jobs(fns, concurrency, progress, total)
  File "/opt/conda/lib/python3.7/site-packages/cloudfiles/scheduler.py", line 38, in schedule_threaded_jobs
    for fn in fns:
  File "/opt/conda/lib/python3.7/site-packages/cloudfiles/cloudfiles.py", line 501, in <genexpr>
    fns = ( partial(uploadfn, file) for file in files )
  File "/opt/conda/lib/python3.7/site-packages/cloudfiles/cloudfiles.py", line 574, in <genexpr>
    (jsonify_file(file) for file in files),
  File "/opt/conda/lib/python3.7/site-packages/cloudfiles/cloudfiles.py", line 566, in jsonify_file
    return (file[0], jsonify(file[1]))
  File "/opt/conda/lib/python3.7/site-packages/cloudfiles/lib.py", line 90, in jsonify
    return orjson.dumps(obj, option=(orjson.OPT_SERIALIZE_NUMPY|orjson.OPT_NON_STR_KEYS), **kwargs)
TypeError: numpy array is not C contiguous; use ndarray.tolist() in default
```

**Comment by supersergiy** [comment]
Is this a worker-side error? I just ran the following command locally, which did not result in any errors:
`corgie normalize \
--src_layer_spec '{"path": "gs://tmacrina-corgie-test/fafbv15_per_island/affine_blockmatch_combined_v1/complete_mip6"}' \
--src_layer_spec '{
      "path":"gs://tmacrina-corgie-test/fafbv15_per_island/affine_blockmatch_combined_v1/complete_mip6",
      "args": {"binarization": ["eq", 0.0]},
      "type": "mask",
      "name": "black_mask"
   }' \
--src_layer_spec '{
      "path":"gs://tmacrina-corgie-test/fafbv15_per_island/affine_blockmatch_combined_v1/folds",
      "args": {"binarization": ["gt", 250], "data_mip": 7},
      "type": "mask",
      "name": "folds"
   }' \
--src_layer_spec '{
      "path":"gs://tmacrina-corgie-test/fafbv15_per_island/affine_blockmatch_combined_v1/cracks",
      "args": {"binarization": ["gt", 250], "data_mip": 7},
      "type": "mask",
      "name": "cracks"
   }' \
--dst_folder "gs://corgie_package/fly/tests/complete_mip6_debug" \
--stats_mip 7 --mip_start 7 --mip_end 7 \
--start_coord "0, 0, 1" \
--end_coord "278400, 130944, 10" \
--chunk_xy 3072 --chunk_z 1 \
--suffix normalized \
--recompute_stats \
--verbose
`

**Comment by supersergiy** [comment]
Looking into it...

**Comment by supersergiy** [comment]
Opened a pull request that solves this
